In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [2]:
heart_df = pd.read_csv("heart.csv")
heart_df.sample(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
216,62,0,2,130,263,0,1,97,0,1.2,1,1,3,0
245,48,1,0,124,274,0,0,166,0,0.5,1,0,3,0
99,53,1,2,130,246,1,0,173,0,0.0,2,3,2,1
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3,0
90,48,1,2,124,255,1,1,175,0,0.0,2,2,2,1
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3,0
268,54,1,0,122,286,0,0,116,1,3.2,1,2,2,0
89,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1

In [4]:
X = heart_df.drop(columns="target")
y = heart_df["target"]

X.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
X_train.sample(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
133,41,1,1,110,235,0,1,153,0,0.0,2,0,2
224,54,1,0,110,239,0,1,126,1,2.8,1,1,3
13,64,1,3,110,211,0,0,144,1,1.8,1,0,2
71,51,1,2,94,227,0,1,154,1,0.0,2,1,3
70,54,1,2,120,258,0,0,147,0,0.4,1,0,3
50,51,0,2,130,256,0,0,149,0,0.5,2,0,2
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
62,52,1,3,118,186,0,0,190,0,0.0,1,0,1
16,58,0,2,120,340,0,1,172,0,0.0,2,0,2
164,38,1,2,138,175,0,1,173,0,0.0,2,4,2

In [7]:
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [8]:
print("Accuracy is: ", accuracy_score(y_test, y_pred))
print("Precision is: ", precision_score(y_test, y_pred))
print("Recall is: ", recall_score(y_test, y_pred))

Accuracy is:  0.8688524590163934
Precision is:  0.9
Recall is:  0.84375